"""Stable internal workflow trace field names.

These constants define the allowed diagnostic field names for internal
workflow traces. They are intentionally metadata-only: callers should store
version identifiers, normalized labels, counts, booleans, TTLs, and hashed
identifiers here instead of raw message text, full IDs, database rows, tokens,
or provider secrets.
"""
from __future__ import annotations

from typing import Final


TRACE_FIELD_ENGINE_BACKEND: Final[str] = "engine_backend"
TRACE_FIELD_WORKFLOW_VERSION: Final[str] = "workflow_version"
TRACE_FIELD_KNOWLEDGE_VERSION: Final[str] = "knowledge_version"
TRACE_FIELD_SOP_VERSION: Final[str] = "sop_version"
TRACE_FIELD_COLLECTION_VERSION: Final[str] = "collection_version"
TRACE_FIELD_SHOP_ID_HASH: Final[str] = "shop_id_hash"
TRACE_FIELD_CHAT_ID_HASH: Final[str] = "chat_id_hash"
TRACE_FIELD_SESSION_ID_HASH: Final[str] = "session_id_hash"
TRACE_FIELD_USER_ID_HASH: Final[str] = "user_id_hash"
TRACE_FIELD_BUYER_ID_HASH: Final[str] = "buyer_id_hash"
TRACE_FIELD_CONVERSATION_ID_HASH: Final[str] = "conversation_id_hash"
TRACE_FIELD_HISTORY_MESSAGE_COUNT: Final[str] = "history_message_count"
TRACE_FIELD_HISTORY_WINDOW_SIZE: Final[str] = "history_window_size"
TRACE_FIELD_PENDING_HUMAN: Final[str] = "pending_human"
TRACE_FIELD_HISTORY_SOURCE: Final[str] = "history_source"
TRACE_FIELD_INTENT: Final[str] = "intent"
TRACE_FIELD_ACTION: Final[str] = "action"
TRACE_FIELD_KNOWLEDGE_SOURCE: Final[str] = "knowledge_source"
TRACE_FIELD_KNOWLEDGE_HIT_COUNT: Final[str] = "knowledge_hit_count"
TRACE_FIELD_SOP_DOMAINS: Final[str] = "sop_domains"
TRACE_FIELD_SOP_RECORD_COUNT: Final[str] = "sop_record_count"
TRACE_FIELD_PRODUCT_CACHE_HIT: Final[str] = "product_cache_hit"
TRACE_FIELD_PRODUCT_CACHE_TTL_SECONDS: Final[str] = "product_cache_ttl_seconds"
TRACE_FIELD_GUARDRAIL_STATUS: Final[str] = "guardrail_status"
TRACE_FIELD_ANSWER_GENERATOR: Final[str] = "answer_generator"
TRACE_FIELD_ANSWER_GENERATOR_PRESENT: Final[str] = "answer_generator_present"
TRACE_FIELD_ANSWER_GENERATOR_TYPE: Final[str] = "answer_generator_type"
TRACE_FIELD_ANSWER_GENERATOR_CALLED: Final[str] = "answer_generator_called"
TRACE_FIELD_ANSWER_GENERATION_SOURCE: Final[str] = "answer_generation_source"
TRACE_FIELD_ANSWER_GENERATION_STATUS: Final[str] = "answer_generation_status"
TRACE_FIELD_ANSWER_ERROR_TYPE: Final[str] = "answer_error_type"
TRACE_FIELD_ANSWER_ERROR_RAW_TYPE: Final[str] = "answer_error_raw_type"
TRACE_FIELD_ANSWER_FAILURE_POLICY: Final[str] = "answer_failure_policy"
TRACE_FIELD_ANSWER_FALLBACK_REASON: Final[str] = "answer_fallback_reason"
TRACE_FIELD_ANSWER_CONFIDENCE: Final[str] = "answer_confidence"
TRACE_FIELD_ANSWER_USED_RAG_HIT_COUNT: Final[str] = "answer_used_rag_hit_count"
TRACE_FIELD_ANSWER_USED_HISTORY_COUNT: Final[str] = "answer_used_history_count"
TRACE_FIELD_USED_HISTORY_COUNT: Final[str] = "used_history_count"
TRACE_FIELD_PROMPT_HASH: Final[str] = "prompt_hash"
TRACE_FIELD_ANSWER_PROMPT_HASH: Final[str] = "answer_prompt_hash"
TRACE_FIELD_RISK_FLAGS: Final[str] = "risk_flags"
TRACE_FIELD_SETS_PENDING_HUMAN: Final[str] = "sets_pending_human"
TRACE_FIELD_ACTIVE_VERSION_RESOLVED: Final[str] = "active_version_resolved"
TRACE_FIELD_ACTIVE_VERSION_ID: Final[str] = "active_version_id"
TRACE_FIELD_ACTIVE_VERSION: Final[str] = "active_version"
TRACE_FIELD_ACTIVE_SOURCE_TYPE: Final[str] = "active_source_type"
TRACE_FIELD_ACTIVE_SOURCE_ID: Final[str] = "active_source_id"
TRACE_FIELD_ACTIVE_DOMAIN: Final[str] = "active_domain"
TRACE_FIELD_ACTIVE_VERSION_FALLBACK: Final[str] = "active_version_fallback"
TRACE_FIELD_ACTIVE_VERSION_MISSING_REASON: Final[str] = "active_version_missing_reason"


INTERNAL_WORKFLOW_TRACE_FIELDS: Final[tuple[str, ...]] = (
    TRACE_FIELD_ENGINE_BACKEND,
    TRACE_FIELD_WORKFLOW_VERSION,
    TRACE_FIELD_KNOWLEDGE_VERSION,
    TRACE_FIELD_SOP_VERSION,
    TRACE_FIELD_COLLECTION_VERSION,
    TRACE_FIELD_SHOP_ID_HASH,
    TRACE_FIELD_CHAT_ID_HASH,
    TRACE_FIELD_SESSION_ID_HASH,
    TRACE_FIELD_USER_ID_HASH,
    TRACE_FIELD_BUYER_ID_HASH,
    TRACE_FIELD_CONVERSATION_ID_HASH,
    TRACE_FIELD_HISTORY_MESSAGE_COUNT,
    TRACE_FIELD_HISTORY_WINDOW_SIZE,
    TRACE_FIELD_PENDING_HUMAN,
    TRACE_FIELD_HISTORY_SOURCE,
    TRACE_FIELD_INTENT,
    TRACE_FIELD_ACTION,
    TRACE_FIELD_KNOWLEDGE_SOURCE,
    TRACE_FIELD_KNOWLEDGE_HIT_COUNT,
    TRACE_FIELD_SOP_DOMAINS,
    TRACE_FIELD_SOP_RECORD_COUNT,
    TRACE_FIELD_PRODUCT_CACHE_HIT,
    TRACE_FIELD_PRODUCT_CACHE_TTL_SECONDS,
    TRACE_FIELD_GUARDRAIL_STATUS,
    TRACE_FIELD_ANSWER_GENERATOR,
    TRACE_FIELD_ANSWER_GENERATOR_PRESENT,
    TRACE_FIELD_ANSWER_GENERATOR_TYPE,
    TRACE_FIELD_ANSWER_GENERATOR_CALLED,
    TRACE_FIELD_ANSWER_GENERATION_SOURCE,
    TRACE_FIELD_ANSWER_GENERATION_STATUS,
    TRACE_FIELD_ANSWER_ERROR_TYPE,
    TRACE_FIELD_ANSWER_ERROR_RAW_TYPE,
    TRACE_FIELD_ANSWER_FAILURE_POLICY,
    TRACE_FIELD_ANSWER_FALLBACK_REASON,
    TRACE_FIELD_ANSWER_CONFIDENCE,
    TRACE_FIELD_ANSWER_USED_RAG_HIT_COUNT,
    TRACE_FIELD_ANSWER_USED_HISTORY_COUNT,
    TRACE_FIELD_USED_HISTORY_COUNT,
    TRACE_FIELD_PROMPT_HASH,
    TRACE_FIELD_ANSWER_PROMPT_HASH,
    TRACE_FIELD_RISK_FLAGS,
    TRACE_FIELD_SETS_PENDING_HUMAN,
    TRACE_FIELD_ACTIVE_VERSION_RESOLVED,
    TRACE_FIELD_ACTIVE_VERSION_ID,
    TRACE_FIELD_ACTIVE_VERSION,
    TRACE_FIELD_ACTIVE_SOURCE_TYPE,
    TRACE_FIELD_ACTIVE_SOURCE_ID,
    TRACE_FIELD_ACTIVE_DOMAIN,
    TRACE_FIELD_ACTIVE_VERSION_FALLBACK,
    TRACE_FIELD_ACTIVE_VERSION_MISSING_REASON,
)

FORBIDDEN_RAW_TRACE_FIELDS: Final[frozenset[str]] = frozenset(
    {
        "content",
        "reply_text",
        "raw_message",
        "raw_db_row",
        "api_key",
        "token",
    }
)


__all__ = [
    "FORBIDDEN_RAW_TRACE_FIELDS",
    "INTERNAL_WORKFLOW_TRACE_FIELDS",
    "TRACE_FIELD_ACTION",
    "TRACE_FIELD_ACTIVE_DOMAIN",
    "TRACE_FIELD_ACTIVE_SOURCE_ID",
    "TRACE_FIELD_ACTIVE_SOURCE_TYPE",
    "TRACE_FIELD_ACTIVE_VERSION",
    "TRACE_FIELD_ACTIVE_VERSION_FALLBACK",
    "TRACE_FIELD_ACTIVE_VERSION_ID",
    "TRACE_FIELD_ACTIVE_VERSION_MISSING_REASON",
    "TRACE_FIELD_ACTIVE_VERSION_RESOLVED",
    "TRACE_FIELD_ANSWER_CONFIDENCE",
    "TRACE_FIELD_ANSWER_ERROR_RAW_TYPE",
    "TRACE_FIELD_ANSWER_ERROR_TYPE",
    "TRACE_FIELD_ANSWER_FAILURE_POLICY",
    "TRACE_FIELD_ANSWER_FALLBACK_REASON",
    "TRACE_FIELD_ANSWER_GENERATION_SOURCE",
    "TRACE_FIELD_ANSWER_GENERATION_STATUS",
    "TRACE_FIELD_ANSWER_GENERATOR",
    "TRACE_FIELD_ANSWER_GENERATOR_CALLED",
    "TRACE_FIELD_ANSWER_GENERATOR_PRESENT",
    "TRACE_FIELD_ANSWER_GENERATOR_TYPE",
    "TRACE_FIELD_ANSWER_PROMPT_HASH",
    "TRACE_FIELD_ANSWER_USED_HISTORY_COUNT",
    "TRACE_FIELD_ANSWER_USED_RAG_HIT_COUNT",
    "TRACE_FIELD_CHAT_ID_HASH",
    "TRACE_FIELD_COLLECTION_VERSION",
    "TRACE_FIELD_CONVERSATION_ID_HASH",
    "TRACE_FIELD_ENGINE_BACKEND",
    "TRACE_FIELD_GUARDRAIL_STATUS",
    "TRACE_FIELD_BUYER_ID_HASH",
    "TRACE_FIELD_HISTORY_MESSAGE_COUNT",
    "TRACE_FIELD_HISTORY_SOURCE",
    "TRACE_FIELD_HISTORY_WINDOW_SIZE",
    "TRACE_FIELD_INTENT",
    "TRACE_FIELD_KNOWLEDGE_HIT_COUNT",
    "TRACE_FIELD_KNOWLEDGE_SOURCE",
    "TRACE_FIELD_KNOWLEDGE_VERSION",
    "TRACE_FIELD_PENDING_HUMAN",
    "TRACE_FIELD_PRODUCT_CACHE_HIT",
    "TRACE_FIELD_PRODUCT_CACHE_TTL_SECONDS",
    "TRACE_FIELD_PROMPT_HASH",
    "TRACE_FIELD_RISK_FLAGS",
    "TRACE_FIELD_SETS_PENDING_HUMAN",
    "TRACE_FIELD_SESSION_ID_HASH",
    "TRACE_FIELD_SHOP_ID_HASH",
    "TRACE_FIELD_USER_ID_HASH",
    "TRACE_FIELD_USED_HISTORY_COUNT",
    "TRACE_FIELD_SOP_DOMAINS",
    "TRACE_FIELD_SOP_RECORD_COUNT",
    "TRACE_FIELD_SOP_VERSION",
    "TRACE_FIELD_WORKFLOW_VERSION",
]
