import Session.session_manager  # Import order avoids existing core/logger circular import in tests.

from Message.workflow.trace_schema import (
    FORBIDDEN_RAW_TRACE_FIELDS,
    INTERNAL_WORKFLOW_TRACE_FIELDS,
    TRACE_FIELD_ACTION,
    TRACE_FIELD_ANSWER_CONFIDENCE,
    TRACE_FIELD_ANSWER_ERROR_RAW_TYPE,
    TRACE_FIELD_ANSWER_ERROR_TYPE,
    TRACE_FIELD_ANSWER_FAILURE_POLICY,
    TRACE_FIELD_ANSWER_FALLBACK_REASON,
    TRACE_FIELD_ANSWER_GENERATION_SOURCE,
    TRACE_FIELD_ANSWER_GENERATION_STATUS,
    TRACE_FIELD_ANSWER_GENERATOR,
    TRACE_FIELD_ANSWER_GENERATOR_CALLED,
    TRACE_FIELD_ANSWER_GENERATOR_PRESENT,
    TRACE_FIELD_ANSWER_GENERATOR_TYPE,
    TRACE_FIELD_ANSWER_PROMPT_HASH,
    TRACE_FIELD_ANSWER_USED_HISTORY_COUNT,
    TRACE_FIELD_ANSWER_USED_RAG_HIT_COUNT,
    TRACE_FIELD_CHAT_ID_HASH,
    TRACE_FIELD_COLLECTION_VERSION,
    TRACE_FIELD_CONVERSATION_ID_HASH,
    TRACE_FIELD_ENGINE_BACKEND,
    TRACE_FIELD_GUARDRAIL_STATUS,
    TRACE_FIELD_BUYER_ID_HASH,
    TRACE_FIELD_HISTORY_MESSAGE_COUNT,
    TRACE_FIELD_HISTORY_SOURCE,
    TRACE_FIELD_HISTORY_WINDOW_SIZE,
    TRACE_FIELD_INTENT,
    TRACE_FIELD_KNOWLEDGE_HIT_COUNT,
    TRACE_FIELD_KNOWLEDGE_SOURCE,
    TRACE_FIELD_KNOWLEDGE_VERSION,
    TRACE_FIELD_PRODUCT_CACHE_HIT,
    TRACE_FIELD_PRODUCT_CACHE_TTL_SECONDS,
    TRACE_FIELD_PROMPT_HASH,
    TRACE_FIELD_PENDING_HUMAN,
    TRACE_FIELD_RISK_FLAGS,
    TRACE_FIELD_SESSION_ID_HASH,
    TRACE_FIELD_SETS_PENDING_HUMAN,
    TRACE_FIELD_SHOP_ID_HASH,
    TRACE_FIELD_USER_ID_HASH,
    TRACE_FIELD_USED_HISTORY_COUNT,
    TRACE_FIELD_SOP_DOMAINS,
    TRACE_FIELD_SOP_RECORD_COUNT,
    TRACE_FIELD_SOP_VERSION,
    TRACE_FIELD_WORKFLOW_VERSION,
)


def test_internal_workflow_trace_fields_are_stable_and_complete():
    assert INTERNAL_WORKFLOW_TRACE_FIELDS == (
        TRACE_FIELD_ENGINE_BACKEND,
        TRACE_FIELD_WORKFLOW_VERSION,
        TRACE_FIELD_KNOWLEDGE_VERSION,
        TRACE_FIELD_SOP_VERSION,
        TRACE_FIELD_COLLECTION_VERSION,
        TRACE_FIELD_SHOP_ID_HASH,
        TRACE_FIELD_CHAT_ID_HASH,
        TRACE_FIELD_SESSION_ID_HASH,
        TRACE_FIELD_USER_ID_HASH,
        TRACE_FIELD_BUYER_ID_HASH,
        TRACE_FIELD_CONVERSATION_ID_HASH,
        TRACE_FIELD_HISTORY_MESSAGE_COUNT,
        TRACE_FIELD_HISTORY_WINDOW_SIZE,
        TRACE_FIELD_PENDING_HUMAN,
        TRACE_FIELD_HISTORY_SOURCE,
        TRACE_FIELD_INTENT,
        TRACE_FIELD_ACTION,
        TRACE_FIELD_KNOWLEDGE_SOURCE,
        TRACE_FIELD_KNOWLEDGE_HIT_COUNT,
        TRACE_FIELD_SOP_DOMAINS,
        TRACE_FIELD_SOP_RECORD_COUNT,
        TRACE_FIELD_PRODUCT_CACHE_HIT,
        TRACE_FIELD_PRODUCT_CACHE_TTL_SECONDS,
        TRACE_FIELD_GUARDRAIL_STATUS,
        TRACE_FIELD_ANSWER_GENERATOR,
        TRACE_FIELD_ANSWER_GENERATOR_PRESENT,
        TRACE_FIELD_ANSWER_GENERATOR_TYPE,
        TRACE_FIELD_ANSWER_GENERATOR_CALLED,
        TRACE_FIELD_ANSWER_GENERATION_SOURCE,
        TRACE_FIELD_ANSWER_GENERATION_STATUS,
        TRACE_FIELD_ANSWER_ERROR_TYPE,
        TRACE_FIELD_ANSWER_ERROR_RAW_TYPE,
        TRACE_FIELD_ANSWER_FAILURE_POLICY,
        TRACE_FIELD_ANSWER_FALLBACK_REASON,
        TRACE_FIELD_ANSWER_CONFIDENCE,
        TRACE_FIELD_ANSWER_USED_RAG_HIT_COUNT,
        TRACE_FIELD_ANSWER_USED_HISTORY_COUNT,
        TRACE_FIELD_USED_HISTORY_COUNT,
        TRACE_FIELD_PROMPT_HASH,
        TRACE_FIELD_ANSWER_PROMPT_HASH,
        TRACE_FIELD_RISK_FLAGS,
        TRACE_FIELD_SETS_PENDING_HUMAN,
    )


def test_internal_workflow_trace_fields_are_unique():
    assert len(INTERNAL_WORKFLOW_TRACE_FIELDS) == len(set(INTERNAL_WORKFLOW_TRACE_FIELDS))


def test_internal_workflow_trace_fields_do_not_include_forbidden_raw_fields():
    forbidden = {"content", "reply_text", "raw_message", "raw_db_row", "api_key", "token"}

    assert FORBIDDEN_RAW_TRACE_FIELDS == forbidden
    assert set(INTERNAL_WORKFLOW_TRACE_FIELDS).isdisjoint(forbidden)


def test_identity_trace_fields_are_hash_only():
    assert "shop_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert "chat_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert "session_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert "buyer_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert "user_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert "conversation_id" not in INTERNAL_WORKFLOW_TRACE_FIELDS
    assert TRACE_FIELD_SHOP_ID_HASH == "shop_id_hash"
    assert TRACE_FIELD_CHAT_ID_HASH == "chat_id_hash"
    assert TRACE_FIELD_SESSION_ID_HASH == "session_id_hash"
    assert TRACE_FIELD_USER_ID_HASH == "user_id_hash"
    assert TRACE_FIELD_BUYER_ID_HASH == "buyer_id_hash"
    assert TRACE_FIELD_CONVERSATION_ID_HASH == "conversation_id_hash"
